version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: farmacia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmacia
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: farmacia-rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI  →  http://localhost:15672  (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
